// Code generated by candi v1.5.32.

package repository

import (
	"context"
	"database/sql"
	"time"

	"pkg.agungdp.dev/candi/candishared"
	shareddomain "monorepo/services/shark/pkg/shared/domain"

	"pkg.agungdp.dev/candi/tracer"
)

type contactRepoSQL struct {
	readDB, writeDB *sql.DB
	tx              *sql.Tx
}

// NewContactRepoSQL mongo repo constructor
func NewContactRepoSQL(readDB, writeDB *sql.DB, tx *sql.Tx) ContactRepository {
	return &contactRepoSQL{
		readDB, writeDB, tx,
	}
}

func (r *contactRepoSQL) FetchAll(ctx context.Context, filter *candishared.Filter) (data []shareddomain.Contact, err error) {
	trace := tracer.StartTrace(ctx, "ContactRepoSQL:FetchAll")
	defer func() { trace.SetError(err); trace.Finish() }()

	if filter.OrderBy == "" {
		filter.OrderBy = "modified_at"
	}
	
	
	return
}

func (r *contactRepoSQL) Count(ctx context.Context, filter *candishared.Filter) (count int) {
	trace := tracer.StartTrace(ctx, "ContactRepoSQL:Count")
	defer trace.Finish()

	var total int64
	count = int(total)
	return
}

func (r *contactRepoSQL) Find(ctx context.Context, data *shareddomain.Contact) (err error) {
	trace := tracer.StartTrace(ctx, "ContactRepoSQL:Find")
	defer func() { trace.SetError(err); trace.Finish() }()

	return
}

func (r *contactRepoSQL) Save(ctx context.Context, data *shareddomain.Contact) (err error) {
	trace := tracer.StartTrace(ctx, "ContactRepoSQL:Save")
	defer func() { trace.SetError(err); trace.Finish() }()
	tracer.Log(ctx, "data", data)

	data.ModifiedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	return
}

func (r *contactRepoSQL) Delete(ctx context.Context, id string) (err error) {
	trace := tracer.StartTrace(ctx, "ContactRepoSQL:Save")
	defer func() { trace.SetError(err); trace.Finish() }()

	return
}
