// Code generated by candi v1.5.32.

package domain

import "time"

// Contact model
type Contact struct {
	ID         string    ` json:"id"`
	CreatedAt  time.Time ` json:"created_at"`
	ModifiedAt time.Time ` json:"modified_at"`
}	
