// Code generated by candi v1.5.32.

package contact

import (
	// "monorepo/services/shark/internal/modules/contact/delivery/graphqlhandler"
	// "monorepo/services/shark/internal/modules/contact/delivery/grpchandler"
	"monorepo/services/shark/internal/modules/contact/delivery/resthandler"
	// "monorepo/services/shark/internal/modules/contact/delivery/workerhandler"
	"monorepo/services/shark/pkg/shared/usecase"

	"pkg.agungdp.dev/candi/codebase/factory/dependency"
	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
)

const (
	moduleName types.Module = "Contact"
)

// Module model
type Module struct {
	restHandler    interfaces.RESTHandler
	grpcHandler    interfaces.GRPCHandler
	graphqlHandler interfaces.GraphQLHandler

	workerHandlers map[types.Worker]interfaces.WorkerHandler
}

// NewModule module constructor
func NewModule(deps dependency.Dependency) *Module {
	usecaseUOW := usecase.GetSharedUsecase()

	var mod Module
	mod.restHandler = resthandler.NewRestHandler(deps.GetMiddleware(), usecaseUOW.Contact(), deps.GetValidator())
	// mod.grpcHandler = grpchandler.NewGRPCHandler(deps.GetMiddleware(), usecaseUOW.Contact(), deps.GetValidator())
	// mod.graphqlHandler = graphqlhandler.NewGraphQLHandler(deps.GetMiddleware(), usecaseUOW.Contact(), deps.GetValidator())

	mod.workerHandlers = map[types.Worker]interfaces.WorkerHandler{
		// types.Kafka:           workerhandler.NewKafkaHandler(usecaseUOW.Contact(), deps.GetValidator()),
		// types.Scheduler:       workerhandler.NewCronHandler(usecaseUOW.Contact(), deps.GetValidator()),
		// types.RedisSubscriber: workerhandler.NewRedisHandler(usecaseUOW.Contact(), deps.GetValidator()),
		// types.TaskQueue:       workerhandler.NewTaskQueueHandler(usecaseUOW.Contact(), deps.GetValidator()),
		// types.PostgresListener: workerhandler.NewPostgresListenerHandler(usecaseUOW.Contact(), deps.GetValidator()),
		// types.RabbitMQ: workerhandler.NewRabbitMQHandler(usecaseUOW.Contact(), deps.GetValidator()),
	}

	return &mod
}

// RESTHandler method
func (m *Module) RESTHandler() interfaces.RESTHandler {
	return m.restHandler
}

// GRPCHandler method
func (m *Module) GRPCHandler() interfaces.GRPCHandler {
	return m.grpcHandler
}

// GraphQLHandler method
func (m *Module) GraphQLHandler() interfaces.GraphQLHandler {
	return m.graphqlHandler
}

// WorkerHandler method
func (m *Module) WorkerHandler(workerType types.Worker) interfaces.WorkerHandler {
	return m.workerHandlers[workerType]
}

// Name get module name
func (m *Module) Name() types.Module {
	return moduleName
}
